server:
  servlet:
    context-path: /
  port: 8080
spring:
  jackson:
    default-property-inclusion: non_null
  application:
    name: PManager
  datasource:
    url: jdbc:mysql://localhost:3306/pmanagerdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1910
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  mongodb:
    host: localhost
    port: 27017
    database: pmanagerdb
app:
  general:
    pageSize: 3
  security:
    masterApiKey: thekey
    expirationDays: 2
